### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by Nicca42** [RibbonBlockchain/IncentivesAlpha#11]
# Log in
A user with a web3 enabled browser goes to the Ribbon dapp. 
The blank dashboards will be filled in at a later stage.

# Acceptance criteria 
These should describe the functionality of the repo _after_ all the work is compleat 
* [x] The user is requested to unlock/connect their wallet
* [x] The user address is checked against the contracts
* [ ] If the user is registered they are shown the relevant dashboard (at this stage they can be blank with text on the page saying their role (i.e CHW, practitioner etc)
* [x] If the user is not registered they are shown a blank page that says "not registered" 

## Technical Implementations/notes
* [x] logging in should be provided using Web3Connect to enable any kind of wallet that the user has to intergrate
* [x] to validate that a user has indeed logged in it should ask them to sign a message.
* [x] redirect after use login should be done to the page of the user type which is retrieved from the smart contract
 
## Supporting documents
@chrismaree please add screenshots

**Comment by RibbonBlockchainRSA** [comment]
Are we using Mobile number to log in?

**Comment by chrismaree** [comment]
> Are we using Mobile numbers to log in?
> Is the public address automatically created and linked to mobile number at this stage?

Nope. You login with your web wallet address which is associated with a phone number when you register

**Comment by KapsonLabs** [comment]
Can we use the phone number for simplicity. And the phone number is tied to the address.

**Comment by RibbonBlockchainRSA** [comment]
Perhaps we need a separate issue for User Registration - to define CHW, Practitioner  & Patient registration/onboarding and KYC process?

**Comment by chrismaree** [comment]
> Can we use the phone number for simplicity. And the phone number is tied to the address.

No, this cant be enough to login because you need to prove ownership of your web3 wallet through the signing of a transaction. Authentication against the API to get your profile information is also a requirement. So when you try get your profile you must send the signed message along with the API request to prove it is indeed the owner of that private key.

**Comment by chrismaree** [comment]
> Perhaps we need a separate issue for User Registration - to define CHW, Practitioner & Patient registration/onboarding and KYC processes in detail?

I agree but this is defined later on in the sprint (the last thing we do actually). @Nicca42 chose this order specifically so that we can get the core functionality down pat assuming the login works and then do the login step. Take a look at issue #16

**Comment by iamonuwa** [comment]
@Nicca42 @chrismaree can I start calling the smart contract now? Need it at this stage
