### ISSUE TITLE
Wallet address not recognised page

### ISSUE THREAD

**Issue by Nicca42** [RibbonBlockchain/IncentivesAlpha#16]
# Wallet address not recognised page
This is the page a user gets directed to if they do not have an address that is registered on the contracts

# Acceptance criteria 
* [x] There is a button in the middle of the page that says "Register with a CHW"
* [x] If the user clicks this button a QR code is displayed on the screen. This QR code is their address in a QR code. 
* [x] They can then show this page to the login step

**Comment by chrismaree** [comment]
@iamonuwa this seems to not work 100%
