### ISSUE TITLE
User transaction tables

### ISSUE THREAD

**Issue by chrismaree** [RibbonBlockchain/IncentivesAlpha#50]
For all user groups we need to see the transactions that have been processed.
This should include the payment amount, the activity done and the CHW that was involved in this. 

This will require pulling from the API for the respective endpoints to get info for diffrent users. 

This will differ based on the user. For CHW there will be slightly more info, patient slightly less info. @GuguNewman will add more details as to what columns should be here for each user group.

**Comment by RibbonBlockchainRSA** [comment]
The Transactions Summary Table on each user Home dashboard will be as follows:

Super Admin
Date, Recorded By (+payout amount), Practitioner (+payout amount), Patient (+payout amount), Activities, Medicines, Ratings, Comments (link), Total Payout, Balance, Status

Health Worker 
Date, Patient (+payout amount) Practitioner (+payout amount) Activities, Medicines, Ratings, Comments (link), Total Payout, Balance, Status

Practitioner
Date, Patient, Activities, Medicines, Comments (link), Ratings, Recorded By, Status, Amount Earned, Total Earned
 
Patient
Date, Activities, Medicines, Amount Earned, Total Balance, (optional....Recorded By, Practitioner)
