### ISSUE TITLE
User specific cards above table

### ISSUE THREAD

**Issue by chrismaree** [RibbonBlockchain/IncentivesAlpha#52]
Wallets need to add a number of user specific cards to show key information for different user groups. 

Admin ones are fine for now.

CHW:
- [ ] Number of patients seen today
- [ ] Number of patients seen last week
- [ ] total patients onboarded

Practitioner:
- [ ] Number of patients seen today
- [ ] Number of patients seen last week
- [ ] Incentives earned to date

Patient:
- [ ] number of visits
- [ ] incentives earned

@GuguNewman please comment below if you want this to change to anything else.

This issue will require input from both @iamonuwa and @KapsonLabs to finish it as API endpoints are required

**Comment by iamonuwa** [comment]
We don't have enough data for this at the moment. I propose this goes to Sprint 4
