### ISSUE TITLE
Implement API endpoints to generate reports

### ISSUE THREAD

**Issue by chrismaree** [RibbonBlockchain/IncentivesAlpha#56]
This issue aims to outline the beginning part of what we need for reporting.  @GuguNewman had identified what is required within the endpoints. This issue is to create the endpoints to generate the json payload for each of the kinds of reports outlined below.

**Comment by RibbonBlockchainRSA** [comment]
The Reports can only be generated by Super Super Admin (Ribbon Blockchain Team)  excepted for where Tenants, CHW and Practitioners have subscribed for a package that allows them to print specific reports.
Reports are outlined by what is required to report on per system User.
Super Admin: 
1. Summary of all transactions report (ability to print by date/selected period)
Date, Recorded By (+payout amount), Practitioner (+payout amount), Patient (+payout amount), Activities, Medicines, Ratings, Comments, Total Payout, Balance, Status
2. Ability and flexibility to select any combination of fields and produce a report e.g
  a) Date, Patient, Medicines
  b) Practitioner, Activities, Ratings 
  c) Recorded By, Total Payout, Status  
  d) Activities, Comments, Medicines 
  etc etc

Health Worker 
1. Summary of all transactions report (ability to print by date/selected period)
Date, Patient (+payout amount) Practitioner (+payout amount) Activities, Medicines, Ratings, Comments, Total Payout, Balance, Status
2. Ability and flexibility to select any combination of fields and produce a report e.g
  a) Date, Patient, Medicines
  b) Practitioner, Activities, Ratings 
  c) Payout by Patient, Activities, Status  
  d) Activities, Comments, Medicines 
  etc etc

Practitioner
1. Summary of all transactions report (ability to print by date/selected period)
Date, Patient, Activities, Medicines, Comments, Ratings, Recorded By, Status, Amount Earned, Total Earned
2. Ability and flexibility to select any combination of fields and produce a report e.g
  a) Date, Patient, Medicines
  b) Activities, Ratings, Amount Earned 
  c) Recorded By, Activities, Comments, 
  etc etc 

Patient
1. Summary of all transactions report (ability to print by date/selected period)
Date, Recorded By, Practitioner, Activities, Medicines, Comments, Status, Ratings, Amount Earned, Total Earned
2. Ability and flexibility to select any combination of fields and produce a report e.g
  a) Date, Activity, Medicines
  b) Activities, Ratings, Amount Earned 
  c) Practitioner, Activities, Comments, 
  etc etc

**Comment by iamonuwa** [comment]
This task is a good candidate for Sprint 4.
