### ISSUE TITLE
Outstanding issues for phase 3

### ISSUE THREAD

**Issue by chrismaree** [RibbonBlockchain/IncentivesAlpha#69]
- [x] Add env file to the react app

- [x] wait zero blocks. right now the front end waits a number of blocks before updating. this should happen instantly.
- [x] payout function still gives RCP message error!!! this one is NBNB.
- [x] only super admin should have donate button. right now it's shown on all users.
- [x] Fix logo. this was not loading in production.
- [x] Add "Ribbon Incentives Ecosystem App" text to "Insert client logo here"
- [x] routing error on logout. If I click logout it did not route me to the login page.

**Comment by iamonuwa** [comment]
Fixed #63
