### ISSUE TITLE
Text styling on dropdown menus is inconsistent

### ISSUE THREAD

**Issue by chrismaree** [RibbonBlockchain/IncentivesAlpha#70]
![image.png](https://images.zenhubusercontent.com/5cb410fcd74bd07972ceb2ad/a4a2de6e-faa4-4a6f-9a01-7e3b556e7fb2)

The text here should be the same as the text here
![image.png](https://images.zenhubusercontent.com/5cb410fcd74bd07972ceb2ad/dbbf6907-9015-4f79-9889-8fc047771e0e)

**Comment by iamonuwa** [comment]
I did the later to accommodate more details about the user. The former, for prescriptions doesn't have more details in it. Am guessing, I should revert the user fields to look the the prescriptions

**Comment by iamonuwa** [comment]
Fixed #63
